baseURL = 'https://santichrist.com/'
locale = 'en-us'
title = "santi's blog"
year = '2026'
theme = 'diary'

[author]
  email = "me@santichrist.com"
  name = "Santi"

[params]
  enableReadingTime = true
  favicon = "/images/favicon-cat.png"

[[menu.main]]
url = "/about"
name = "who is santi?"
weight = 1

[[menu.main]]
url = "/diary"
name = "my diary"
weight = 2

[[menu.main]]
url = "/music"
name = "my music"
weight = 3

[[menu.main]]
url = "/links"
name = "my links"
weight = 4

[[menu.main]]
url = "/lists"
name = "my takes"
weight = 5
