baseURL = 'https://santichrist.com/'
locale = 'en-us'
title = "santi's blog"
year = '2026'
theme = 'diary'

[author]
  email = "me@santichrist.com"
  name = "Santi"

[params]
  enableReadingTime = true
  favicon = "static/images/favicon-cat.png"

[[menu.main]]
url = "/categories"
name = "Categories"
weight = 3

[[menu.main]]
url = "/tags"
name = "Tags"
weight = 2

[[menu.main]]
url = "/posts"
name = "Archive"
weight = 1
